### ISSUE TITLE
CS0433 Conflict between OpenTelemetry and Telemetry packages

### ISSUE THREAD

**Issue by rurounijones** [newrelic/newrelic-telemetry-sdk-dotnet#161]
## Description

I am using the OpenTelemetry exporter to export traces to NewRelic. However I also want to export Metrics. Currently there is no OpenTelemetry integration for exporting metrics so I am trying to use the Telemetry package to send metrics directly.

However including both nuget packages in the project results in the following:

```plain
CS0433: The type 'TelemetryConfiguration' exists in both 
'NewRelic.Telemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=82b1ac20087f0ac7'
'OpenTelemetry.Exporter.NewRelic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=82b1ac20087f0ac7'
```

It seems there might be a workaround but it does not appear to me working for me unfortunately (Possibly due to my inexperience with C# and getting it wrong) https://stackoverflow.com/questions/33460667/how-to-use-extern-alias-with-nuget

## Steps to Reproduce

Create a C# project and add the two nuget packages from this Repo via nuget.

## Expected Behaviour

I am able to use the `NewRelic.Telemetry` package without issues until OpenTelemetry Metrics exporting is enabled.

**Comment by alanwest** [comment]
@rurounijones Please try the latest version of our exporter package. It has been renamed to `NewRelic.OpenTelemetry` https://www.nuget.org/packages/NewRelic.OpenTelemetry. The package was renamed in preparation for the upcoming GA of OpenTelemetry, so that all of our packages are prefixed with `NewRelic.*`.

I believe this issue should be remedied in when using the latest packages.

**Comment by rurounijones** [comment]
Will give it a try, thank you for the quick response.

For completeness sake I also got the alias method working using the following

csproj file
```
  <Target Name="ChangeAliasesOfNugetRefs" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'NewRelic.Telemetry'">
        <Aliases>workaround</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

code
```csharp
extern alias workaround;
using workaround::NewRelic.Telemetry;

// <snip>

TelemetryConfiguration telemetryConfig = new TelemetryConfiguration();
```

**Comment by rurounijones** [comment]
Confirmed latest betas play nicely with each other. Apologies for not noticing later versions were available.

**Comment by alanwest** [comment]
Great, glad that resolved things for you! Also thanks for the tip regarding the alias - didn't know this was a thing!
