### ISSUE TITLE
Support for OpenTelemetry Events on a Span

### ISSUE THREAD

**Issue by AndrewRissing** [newrelic/newrelic-telemetry-sdk-dotnet#186]
Add support for OpenTelemetry [Events](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events), which allow for reporting an event at a specific time with attributes.

**Comment by alanwest** [comment]
Thanks, @AndrewRissing! This is certainly something that is on New Relic's radar.

Unfortunately, it's a bit more involved than just enabling sending up events from our exporter - that is, New Relic's backend does not yet support ingesting OTel events and therefore we do not currently display OTel event data anywhere in our UIs.

Though, I am curious about your use cases for using events. The OpenTelemetry community has a few that I am aware of:

1. recording exceptions
2. gRPC messages
3. logs
4. adding custom events

Are there particular use cases you're interested in?

**Comment by AndrewRissing** [comment]
I had assumed the limitation existed on the backend,  based on what I've seen.  For us, we're really looking at it for events (#4) with handled exceptions (#1) being a special case of that.

Perhaps some synergy might exist between NR's concept of an event and OTel events, but that might be a bit presumptuous based on how NR's backend is setup.

**Comment by Tragedian** [comment]
I'm expecting precise timing events to be included in spans. For example, the [StackExchange Redis client instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md) adds events for each step in the command-processing pipeline:
- Enqueued
- Sent
- ReponseRecieved

(see: [RedisProfilerEntryToActivityConverter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs#L99))

This information is critical for diagnosing performance bottlenecks around Redis use.

**Comment by iSeiryu** [comment]
I'd like to see logging capabilities: system, custom, and exceptions.
I was able to attach them to the current Activity and send them to Jaeger here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1739#issuecomment-777841656

I tried to use the same approach for NR:
```csharp
.AddNewRelicExporter(options => {
    options.ApiKey = "my-key";
    options.ExportProcessorType = ExportProcessorType.Batch;
})
```
I was hoping to at least get an error message when an exception occurs but all I get is this
![image](https://user-images.githubusercontent.com/129137/107859762-a829ba00-6e09-11eb-86dd-1ac2ed9e9ad7.png)

I also tried to manually add tags like this
```csharp
{ "error.message", data.Exception }
```
and
```csharp
Activity.Current.SetTag("error.message", data.Exception);
```

**Comment by iSeiryu** [comment]
About error logging.
According to the OpenTelemetry spec it has these fields
```
attributes["error.code"]
attributes["error.id"]
attributes["error.message"]
attributes["error.stack_trace"]
```

If I add my exception like this
```cshapr
activity.SetTag("error.message", data.Exception.Message)
        .SetTag("error.stack_trace", data.Exception.StackTrace);
```
then NR actually sees the stack trace but refuses to get the message

![image](https://user-images.githubusercontent.com/129137/107887121-c824b080-6ed1-11eb-9a94-c3109f8a7422.png)

I tested the same code on Zipkin and Jaeger and both take my fields as expected. It looks like a bug.

**Comment by nrcventura** [comment]
Hi @iSeiryu thank you for experimenting with different options for getting the information you want sent to New Relic.

> I'd like to see logging capabilities: system, custom, and exceptions.

This is something on New Relic's radar, but is not currently supported by this exporter. In the meantime you should still be able to send your logs to New Relic using the methods defined in our [log management getting started documentation](https://docs.newrelic.com/docs/logs/log-management/get-started/get-started-log-management).

> I was hoping to at least get an error message when an exception occurs but all I get is `Unspecified error`

New Relic gets error information based on the span specifications where error information is added to `otel.status_code` and `otel.status_description`, which is what the [Jaeger exporter is supposed to do as well](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#status). The New Relic exporter [currently uses](https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/blob/main/src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs#L233-L244) `otel.status_description` to define an `error.message` tag. You should be able to use the [SetStatus api](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) to control both the status code and status description for the span. There is an [extension method](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L42-L50) in the OTel SDK for .NET that can help you with setting this status code.

> If I add my exception like this
> ```csharp
>activity.SetTag("error.message",     data.Exception.Message)
>        .SetTag("error.stack_trace", data.Exception.StackTrace);
>```
> then NR actually sees the stack trace but refuses to get the message

This is a result of New Relic using `otel.status_description` to create an `error.message` tag for you, so New Relic is treating `error.message` as a tag that would be ignored if it was directly set on a span. The list of all reserved tag names in use by the exporter can be seen [here](https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/blob/main/src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs#L28-L39).

**Comment by Tragedian** [comment]
Is there any provision for associating events with a span in NewRelic? I'd be happy to do some custom work with my exporter and telemetry to shape the data to what NewRelic needs, but I don't see a way to get the associated information in there.

In my specific case, I want to know how much time in a Redis interaction was spent on the network. Visually, this could be splitting the span into sub-activities, or otherwise delineating sections of time between key events. Any suggestions on how we might do this?

**Comment by nrcventura** [comment]
For everyone wanting to see their events on spans within New Relic, there is a new option that you may want to consider. Instead of using this exporter to send your data to New Relic, you can send your data to New Relic using the OTLP exporter provided by the .NET OTel SDK. We’re currently running a pre-release for our native OTLP endpoint, which includes support for sending events on spans to New Relic. The events on spans are currently available to query via NRQL using something like `SELECT * FROM SpanEvent where trace.id = '<traceId>'`.

[Here's the sign-up form](https://forms.gle/fa2pWcQxgVQYMggEA) if you’re interested.
