### ISSUE TITLE
API does not get read. 

### ISSUE THREAD

**Issue by Jay-Shah10** [newrelic/newrelic-telemetry-sdk-dotnet#193]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
Trying to set up this SDK and when executed the API does not get recognized. API key is added in as an environmental variable. 
public const string ApiKey = "NewRelicApiKey";

The error that comes out: 
2021-02-25T20:01:51.4212101Z:New Relic: '{0}'{System.ArgumentNullException: Value cannot be null. (Parameter 'Configuration requires API key')}

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

API Key is recognized and accepted and data flows into New Relic.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* DotNet

**Comment by alanwest** [comment]
The exporter does not look up the API via an environment variable.

The following example demonstrates how to set the API key

https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/blob/c18541085a7f3a816c6d91d3b66afe858f27bab9/examples/NewRelic.OpenTelemetry/AspNetCore/Startup.cs#L36-L39

You could change this like to use `System.Environment.GetEnvironmentVariable("YOUR_ENV_VAR_WITH_NR_API_KEY")`

Closing this issue. Feel free to reopen if you still have issues.
