### ISSUE TITLE
Add the "instrumentation.provider" attribute to exported spans and metrics

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-dotnet#75]
## Summary

Add the "instrumentation.provider" attribute to exported spans and metrics. This is specified here:  https://github.com/newrelic/newrelic-exporter-specs/blob/master/opentelemetry/OpenTelemetry-Spans.md

## Desired Behaviour
Consistent behavior across opentelemetry language exporters.

**Comment by jifeingo** [comment]
Released in v1.0.0-beta.134
