### ISSUE TITLE
Unable to run sample app with OpenTelemetry.Exporter from Nuget

### ISSUE THREAD

**Issue by leslie-alldridge** [newrelic/newrelic-telemetry-sdk-dotnet#85]
## Description

When running the sample application we notice the relative URL being used here
https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/blob/master/src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj#L14

It doesn't work however if we change it to reference Nuget

The error that appears is:
Unhandled exception. System.TypeLoadException: Method 'ExportAsync' in type 'OpenTelemetry.Exporter.NewRelic.NewRelicTraceExporter' from assembly 'OpenTelemetry.Exporter.NewRelic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=82b1ac20087f0ac7' does not have an implementation.

## Steps to Reproduce

Download the sample application called SampleAspNetCoreApp and type `dotnet run`

## Expected Behaviour

API should run

## Relevant Logs / Console output

Error posted above

## Your Environment
Windows 10 64 bit, latest Chrome

**Comment by alanwest** [comment]
@leslie-alldridge Thanks for bringing this to our attention! The package on nuget.org was not up to date. I have published version `1.0.0-beta.157` which should resolve things for you. I will close this issue, but let us know if you run into any other issues.
