### ISSUE TITLE
Add note to Readme to indicate that OpenTelemetry.Extensions.Hosting must be installed

### ISSUE THREAD

**Issue by WhitWaldo** [newrelic/newrelic-telemetry-sdk-dotnet#91]
Installing the NuGet package isn't sufficient in itself to also assemble the example as provided in the readme. Rather, one must also install the [OpenTelemetry.Extensions.Hosting](https://www.nuget.org/packages/OpenTelemetry.Extensions.Hosting/0.4.0-beta.2) package in order to have the AddOpenTelemetry extension method available against IServiceCollection.

**Comment by alanwest** [comment]
Thanks for bringing this to our attention @WhitWaldo! Looks like there are a number of things out of sync in our readme. As OpenTelemetry is still in beta, the likelihood of this continuing to get out of sync is high.

In the meantime, I think what I will do will be to remove the code samples from the readme and instead link to our sample projects which we keep current and ensure compiles against the correct OpenTelemetry dependencies.

Here's our AspNetCore [example](https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/tree/master/src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetCoreApp).
