### ISSUE TITLE
Platform Independence (Development Environment)

### ISSUE THREAD

**Issue by kolanos** [newrelic/newrelic-telemetry-sdk-dotnet#99]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )
Update this library to follow patterns similar to `opentelemetry-dotnet` where it can be built and tested on platforms other than Windows, specifically Linux and OSX / Mac OS.

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
When `dotnet build` or `dotnet test` are run on this project it works on Windows, Linux and OSX / Mac OS.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )
I assume the target frameworks need to change here, as they're different from the ones used by `opentelemetry-dotnet`. However, I don't have enough C# knowledge yet to know what other changes are needed for this to work.

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
This enhancement would increase the developer/contributor base considerably. It would also be useful to document development environment setup for supported platforms and how to run builds and tests.

**Comment by alanwest** [comment]
Thanks @kolanos. Agreed this project should be able to be built on all platforms. I've got a PR which we'll get merged soon. I've tested on OSX. I've no reason to believe things wouldn't work on Linux, though I haven't tried yet.
